[#26] docs: 이직/취업 준비에 도움되는 사이트 모음 컨텐츠 작성
geultto/geultto.github.io pull request #28
Opened 2024-11-22 12:12 UTC by dldydtjs2965

## 작업 내용
- 이직/취업에 도움되는 인사이트를 제공하기 위한 컨텐츠 작성
- 주제
  - 취업 플랫폼
  - 기업 정보 사이트
  - 코딩 테스트
  - 이력서 작성
  - 기술 면접

## 공유사항
코드 트리는 재휘님의 의견을 받아 작성했습니다. 이외에 내용들은 제 주관적인 생각들을 기반으로 제가 작성해봤습니다.

2024-11-22 13:02 UTC, zzsza requested changes
맞춤법 검사랑 이미지 확인, URL 등 확인해봤어요.

2024-11-22 13:02 UTC, zzsza commented on blog/recommended/job-insight.mdx
> +기업 리뷰라는 개념을 초기에 만든 서비스인 만큼 다양한 기업과 많은 수의 리뷰가 있는 서비스 입니다. 유료 결제를 통해 리뷰 확인이 가능하며 만약 제휴 중인 대학교의 메일이 존재하면 해당 메일로
```suggestion
기업 리뷰라는 개념을 초기에 만든 서비스인 만큼 다양한 기업과 많은 수의 리뷰가 있는 서비스입니다. 유료 결제를 통해 리뷰 확인이 가능하며 만약 제휴 중인 대학교의 메일이 존재하면 해당 메일로
```

2024-11-22 13:02 UTC, zzsza commented on blog/recommended/job-insight.mdx
> +계정 가입을 통해 리뷰 조회가 가능합니다. 기업에 대한 후기 뿐만 아니라 면접, 복지 등에 대한 정보들도 볼 수 있습니다.
```suggestion
계정 가입을 통해 리뷰 조회가 가능합니다. 기업에 대한 후기뿐만 아니라 면접, 복지 등에 대한 정보들도 볼 수 있습니다. 
```

2024-11-22 13:02 UTC, zzsza commented on blog/recommended/job-insight.mdx
> +계정 가입을 통해 리뷰 조회가 가능합니다. 기업에 대한 후기 뿐만 아니라 면접, 복지 등에 대한 정보들도 볼 수 있습니다.
밑에 부분은 용선님이 맞춤법 검사기 돌려주시면 좋을 것 같아요. 제가 다른 일정이 있어서, 일단 여기까지 맞춤법 확인했어용

2024-11-24 02:29 UTC, dldydtjs2965 commented on blog/recommended/job-insight.mdx
> +그리고 기업과 연계하여 인턴십이나 채용 행사를 열기 때문에 대규모 채용 기회를 노리기 유용합니다.
아하 그렇군요 수정해보도록 하겠습니다~!

2024-11-24 07:26 UTC, dldydtjs2965 commented on blog/recommended/job-insight.mdx
> +### **단점**
글또 분이 제가 소개한 회사에 재직할 수 있다는 생각을 미처 고려하지 못했네요. 좋은 피드백 감사합니다. 부정적인 키워드가 되지 않도록 `참고하면 좋은 점`이라는 키워드로 바꿔서 올려보도록 하겠습니다!

2024-11-24 07:27 UTC, dldydtjs2965 commented on blog/recommended/job-insight.mdx
> +그런 이유를 몇가지 추측해보자면 채용 수수료가 들지 않는 다는 점, 내부 시스템을 통해 인재를 쉽고 편리하게 관리할 수 있다.
전체적으로 띄어쓰기와 맞춤법 틀린 부분이 있어서 맞춤법 검사기로 전부 문장을 검토해 수정했습니다~! 체크해주셔서 감사합니다.

2024-11-24 08:36 UTC, KumJungMin commented
좋은 정보가 많은 거 같습니다 :)
추가적으로 시간적 여유가 된다면, 사이트 링크도 같이 걸어주면 어떨까 제안해봅니다ㅎㅎ

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +다른 채용 플랫폼과의 차이점이 있다면 인재를 서칭하고 제안을 전달하는 기능들이 잘 갖추고 있어 프로필을 잘 작성해놓으면 많은 기업에서 종종 제안이 들어옵니다.
- 조사를 수정하면, 문장 연결이 매끄러워질 듯 합니다 :)
```suggestion
다른 채용 플랫폼과의 차이점이 있다면 인재를 서칭하고 제안을 전달하는 기능들을 잘 갖추고 있어 프로필을 잘 작성해놓으면 많은 기업에서 종종 제안이 들어옵니다.
```

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +- 공고 수와 포지션의 종류가 타 플랫폼 대비 압도적으로 많습니다
- 온점(.)이 빠진 거 같아용!
```suggestion
- 공고 수와 포지션의 종류가 타 플랫폼 대비 압도적으로 많습니다.
```

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +IT 관련 취업 플랫폼 중 가장 큰 플랫폼인 만큼 채용 공고 수와 기업들도 많고 취업이나 이직을 준비하는 것에 있어서 유익한 컨텐츠와 유익한 행사들도 많습니다.
작성해주신 문장에서 '유익한 컨텐츠와 유익한 행사들도 많습니다.'를 '유익한 컨텐츠와 행사들도 많습니다.'로 살짝 다듬으면 어떨까요? 같은 단어가 반복되는 느낌을 줄이면서 더 자연스럽게 읽힐 것 같아요! 😊
```suggestion
IT 관련 취업 플랫폼 중 가장 큰 플랫폼인 만큼 채용 공고 수와 기업들도 많고 취업이나 이직을 준비하는 것에 있어서 유익한 컨텐츠와 행사들도 많습니다.
```

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +- 이력서를 작성할 때 깃허브와 연동이 가능하기 때문에 저의 스킬을 소개할 때 유용합니다.
```suggestion
- 이력서를 작성할 때 깃허브와 연동이 가능하기 때문에 자신의 스킬을 소개할 때 유용합니다.
```
글을 읽는 사람이 자신의 입장에서 이해할 수 있도록, '저의 스킬'을 '자신의 스킬'로 바꿔보는 건 어떨까요? 
이렇게 하면 독자의 관점에서 더 자연스럽게 다가올 것 같아요!

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +- 코딩 테스트가 함께 진행하는 공고가 많다 보니 알고리즘이 약하다면 불리할 수 있습니다.
```suggestion
- 코딩 테스트를 함께 진행하는 공고가 많다 보니 알고리즘이 약하다면 불리할 수 있습니다.
```
조사를 변경하면 문장 연결이 자연스러워 질 거 같아요 :)

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +채용 플랫폼에 종속되지 않고 기업 내부 규정에 맞춰 진행할 수 있기 때문에 우선적으로 검토할 것이라 생각합니다(저의 가설입니다)
```suggestion
채용 플랫폼에 종속되지 않고 기업 내부 규정에 맞춰 진행할 수 있기 때문에 우선적으로 검토할 것이라 생각합니다. (저의 가설입니다.)
```
- 온점(.)이 필요해보입니당

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +#### **참고하면 좋았던 점**
```suggestion
#### **참고하면 좋은 점**
```
제목 오타인 거 같아요!

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +- 각 기업에 인재풀에 등록할 수 있도록 유도하는 경우가 있기 때문에 개인 인사 정보가 기업 내부에 등록될 수 있습니다.
```suggestion
- 각 기업의 인재풀에 등록할 수 있도록 유도하는 경우가 있기 때문에 개인 인사 정보가 기업 내부에 등록될 수 있습니다.
```
조사를 수정하면 문장 연결이 자연스러울 거 같습니다~!

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +단 회원가입이 필수적으로 요구하고 특정 기능에 대해서는 유료로 제공하기 때문에 결제해야 합니다.
```suggestion
단, 회원가입이 필수적으로 요구되며 특정 기능은 유료로 제공하기 때문에 결제해야 합니다.
```
이렇게 수정해보면 어떨까요? :)

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +많은 직장인들이 활용하는 플랫폼이며 재직하고 있는 근로자와의 채팅도 이야기를 나눌 수 있는 커뮤니티입니다. 알다시피 회사에 대한 리뷰도 있는데 직장에 있는 메일로 가입을 하고 리뷰를 남겨야지만 확인할 수 있습니다.
```suggestion
많은 직장인들이 활용하는 플랫폼이며, 재직자와 채팅으로 이야기를 나눌 수 있는 커뮤니티입니다. 알다시피 회사에 대한 리뷰도 있는데 직장에 있는 메일로 가입을 하고 리뷰를 남겨야지만 확인할 수 있습니다.
```

2024-11-24 08:36 UTC, KumJungMin commented on blog/recommended/job-insight.mdx
> +  <img src="https://contents.nextunicorn.kr/company/023c1582d1220184/rep-1a0e17a56aef766cdecd11aaff63a99b1814.png?s=640x&t=cover&f=jpg" width="500px" height="400px" />
블라인드 이미지 비율이 깨지는 거 같아용! `height="auto"`로 처리해서 비율을 유지하면 어떨까요? :)

<img width="1272" alt="스크린샷 2024-11-24 오후 5 34 34" src="https://github.com/user-attachments/assets/70537ba9-559b-4a99-a216-7c8ef963a1b1">

2024-11-24 08:51 UTC, KumJungMin approved these changes
컨텐츠 크루의 첫 번째 글이네요! 
글 작성하시느라 고생하셨습니당 덕분에 시작이 좋습니당~! 👍 👍

2024-11-24 09:37 UTC, zzsza approved these changes

2024-11-24 10:08 UTC, merged